const styles = {
  root: {
    backgroundColor: "white",
    border: "1px solid black",
    borderRadius: "5px",
    padding: "0.5rem",
    position: "relative",
    overflow: "hidden",
    cursor: "pointer",
    "&:hover svg": { opacity: 1 },
  },
  colors: {
    backgroundColor: "#dae1e4 !important",
    height: "150px !important",
    width: "100% !important",
    borderRadius: "5px !important",
    overflow: "hidden !important",
  },
  title: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    margin: 0,
    color: "black",
    paddingTop: "0.5rem",
    fontSize: "1rem",
    position: "relative",
  },
  emoji: { marginLeft: "0.5rem", fontSize: "1.5rem" },
  miniColor: {
    height: "25% !important",
    width: "20% !important",
    display: "inline-block !important",
    margin: "0 auto !important",
    position: "relative !important",
    marginBottom: "-4px !important",
  },
  deleteIcon: {
    color: "white",
    backgroundColor: "#eb3d30",
    width: "20px",
    height: "20px",
    position: "absolute",
    right: "0",
    top: "0",
    padding: "10px",
    zIndex: 10,
    opacity: 0,
  },
};
export default styles;
